# Generated by Django 4.2.11 on 2024-04-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_email_created_at_alter_email_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='redemptions_count',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
