# Generated by Django 4.2.11 on 2024-05-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_email_deleted_at_alter_order_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='redemptions_count',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
    ]
